alexandresoro/ouca

packages/frontend/src/components/notifications/NotificationSnackbar.tsx
packages/frontend/src/index.css

fix: change z-index in modals & snackbar to always have snackbars above

---

packages/frontend/src/components/inventory/inventory-form/InventoryForm.tsx
packages/frontend/src/components/inventory/inventory-form/InventoryFormObserver.tsx
packages/frontend/src/components/inventory/inventory-form/InventoryFormWeather.tsx

fix(inventory): missing initial associates and weathers

---

packages/common/src/api/entry.ts

fix(entry): prevent duplicates in behaviors and environments

---

packages/backend/src/services/entities/espece-service.spec.ts
packages/backend/src/services/entities/espece-service.ts
packages/backend/src/services/services.ts
packages/common/src/entities/species.ts
packages/frontend/src/components/entry/entry-form/EntryFormSpecies.tsx
packages/frontend/src/components/manage/espece/EspeceTable.tsx
packages/frontend/src/components/search/search-species-table/SearchSpeciesTable.tsx

feat(entry): prefill species class on form if provided

---

packages/backend/src/repositories/donnee/donnee-repository-helper.ts
packages/backend/src/repositories/inventaire/inventaire-repository-helper.ts
packages/backend/src/repositories/repository-helpers.spec.ts
packages/backend/src/repositories/repository-helpers.ts
packages/backend/src/repositories/search-criteria.ts

fix: handle "null" value whenever filtering data

---

packages/frontend/src/components/common/styled/select/AutocompleteMultiple.tsx

fix(autocomp-mult): wrong behavior when selecting options via click

---

packages/backend/src/repositories/age/age-repository.ts
packages/backend/src/repositories/classe/classe-repository.ts
packages/backend/src/repositories/commune/commune-repository.ts
packages/backend/src/repositories/comportement/comportement-repository.ts
packages/backend/src/repositories/departement/departement-repository.ts
packages/backend/src/repositories/espece/espece-repository-helper.ts
packages/backend/src/repositories/estimation-distance/estimation-distance-repository.ts
packages/backend/src/repositories/estimation-nombre/estimation-nombre-repository.ts
packages/backend/src/repositories/lieudit/lieudit-repository.ts
packages/backend/src/repositories/meteo/meteo-repository.ts
packages/backend/src/repositories/milieu/milieu-repository.ts
packages/backend/src/repositories/observateur/observateur-repository.ts
packages/backend/src/repositories/sexe/sexe-repository.ts

feat(entities): unaccented queries

---

packages/frontend/src/components/entry/entry-summary-panel/EntrySummaryPanel.tsx

fix(entry): summary should display distance 0

---

packages/backend/src/fastify.ts

check if it fixes issue with "Location" headers losing protocol info

fix(fastify): add trust proxy to rely on X-Forwarded-* headers

---

packages/common/src/api/locality.ts

fix(locality): validation on altitude to allow only integer values

---

packages/frontend/src/components/entry/entry-map/EntryMap.tsx
packages/frontend/src/utils/map/bounding-polygon.ts

fix(map): no zoom whenever less than 3 localities were defined

---

packages/frontend/src/components/common/maps/localities-layers.ts
packages/frontend/src/components/entry/entry-map/EntryMap.tsx

fix(map): stacktrace when displaying layers initially

---

packages/frontend/src/index.css

feat(popover): add some backdrop-blur to improve legibility

---

packages/frontend/src/components/common/form/FormAutocomplete.tsx
packages/frontend/src/components/common/form/FormAutocompleteMultiple.tsx
packages/frontend/src/components/common/form/FormSelect.tsx
packages/frontend/src/components/common/styled/Checkbox.tsx
packages/frontend/src/components/common/styled/RequiredField.tsx
packages/frontend/src/components/common/styled/Switch.tsx
packages/frontend/src/components/common/styled/TextArea.tsx
packages/frontend/src/components/common/styled/TextInput.tsx
packages/frontend/src/components/common/styled/select/Autocomplete.tsx
packages/frontend/src/components/common/styled/select/AutocompleteMultiple.tsx
packages/frontend/src/components/common/styled/select/Select.tsx
packages/frontend/src/components/entry/entry-form/EntryFormCharacteristics.tsx
packages/frontend/src/components/entry/entry-form/EntryFormSpecies.tsx
packages/frontend/src/components/inventory/inventory-form/InventoryFormLocation.tsx
packages/frontend/src/components/inventory/inventory-form/InventoryFormObserver.tsx
packages/frontend/src/components/manage/commune/CommuneEdit.tsx
packages/frontend/src/components/manage/comportement/ComportementEdit.tsx
packages/frontend/src/components/manage/espece/EspeceEdit.tsx
packages/frontend/src/components/manage/lieu-dit/LieuDitEdit.tsx

feat: add indicator on required fields

---

packages/common/src/api/town.ts

fix(town): improve code validation

---

packages/frontend/src/utils/sentry.ts

feat(sentry): filter out analytics errors

---

packages/backend/src/controllers/inventories-controller.ts
packages/backend/src/objects/import/imported-donnee.object.ts
packages/backend/src/services/entities/inventaire-service-reshape.spec.ts
packages/backend/src/services/entities/inventaire-service-reshape.ts
packages/backend/src/services/entities/inventaire-service.spec.ts
packages/backend/src/utils/utils.ts
packages/backend/vite.config.ts
packages/common/src/api/inventory.ts
packages/common/src/utils/time-format-convert.spec.ts
packages/common/src/utils/time-format-convert.ts
packages/frontend/public/locales/fr/translation.json
packages/frontend/src/components/common/styled/TextInput.tsx
packages/frontend/src/components/inventory/inventory-form/InventoryFormDate.tsx

feat(inventory): allow and harmonize patterns for duration

---

packages/frontend/public/locales/fr/translation.json
packages/frontend/src/features/manage/meteo/MeteoTable.tsx

feat(weather): add legend for wind and cloud cover

---

packages/frontend/package.json
pnpm-lock.yaml

Reverts alexandresoro/ouca#2259

Revert "chore(deps): bump protomaps-themes-base from 2.0.0-alpha.5 to 2.0.0-alpha.6"

---

packages/frontend/package.json
pnpm-lock.yaml

Reverts alexandresoro/ouca#2592
See https://github.com/maplibre/maplibre-gl-js/issues/4340

Revert "fix(deps): update dependency maplibre-gl to v4.5.0"
